language: cpp
compiler:
 - clang
 - gcc
os:
 - linux
 - osx
install:
 - cd Thirdparty/
 - ./get.ASL
 - cd ..
 - make
script:
 - test -x bin/gjh_asl_json
 - test -f lib/libAmplInterface.a
 - make clean
 - "! test -f bin/gjh_asl_json"
 - "! test -f lib/libAmplInterface.a"
