language: cpp
sudo: false
matrix:
  include:
    - os: linux
      compiler: clang
      env: COVCMD="llvm-cov"
    - os: linux
      compiler: gcc
      env: COVCMD="gcov"
    - os: osx
      compiler: clang
      env: COVCMD="llvm-cov"
    - os: osx
      compiler: gcc
      env: COVCMD="gcov"
install:
 - cd Thirdparty/
 - ./get.ASL
 - cd ..
 - make COVERAGE="-coverage -O0"
script:
 - echo ${COVCMD}
 - test -x bin/gjh_asl_json
 - cd tests/
 - bash runtests.sh
 - cd ..
 - ${COVCMD} src/*
after_success:
 - bash <(curl -s https://codecov.io/bash)
after_script:
 - make clean
 - "! test -f bin/gjh_asl_json"
